infinispan:
  cluster:
    name: Kamehameha
    statistics.enabled: true
    jgroups.config:
    network.address: 127.0.0.1

  hotrod:
    # Infinispan default is 10,000
    topologyLockTimeout: 30000 # ms
    topologyReplTimeout: 30000 # ms

  cache:
    primary:
      name: main
      mode: REPL_ASYNC
      stateTransferChunkSize: 128
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024
      numOwners: 3 # Amount of machines in the cluster storing the key

    secondary:
      name: session
      mode: REPL_SYNC
      stateTransferChunkSize: 128
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024
      numOwners: 3 # Amount of machines in the cluster storing the key

    readthrough:
      name: readthrough
      mode: REPL_ASYNC
      stateTransferChunkSize: 128
      enabled: false
      preload: false
      preloadPageSize: 5000
      entityClass: com.zalora.aloha.domain.CacheItem
      persistenceUnitName: org.infinispan.persistence.jpa
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024

jgroups:
  aws: false
  aws_ping:
    tags:
    filters:
    access_key:
    secret_key:

spring:
  datasource:
    url:
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
    testWhileIdle: false

server.port: 8080
logging.level.root: INFO
management.security.enabled: false
endpoints.shutdown.enabled: true

---
spring.profiles: aws_ping

infinispan:
  cluster:
    jgroups.config: jgroups-aws.xml
