infinispan:
  cluster:
    name: Kamehameha
    statistics.enabled: true
    jgroups.config:
    network.address: 127.0.0.1

  hotrod:
    # Infinispan default is 10,000
    topologyLockTimeout: 30000 # ms
    topologyReplTimeout: 30000 # ms

  cache:
    primary:
      name: main
      mode: REPL_ASYNC
      stateTransferChunkSize: 128
      numOwners: 3 # Amount of machines in the cluster storing the key
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024
      readthrough:
        enabled: false
        preload: false
        preloadPageSize: 5000
        entityClass: com.zalora.aloha.memcached.MemcachedItem
        persistenceUnitName: readthroughJPA

    secondary:
      name: session
      mode: REPL_SYNC
      stateTransferChunkSize: 128
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024
      numOwners: 3 # Amount of machines in the cluster storing the key

spring:
  datasource:
    url:
    username:
    password:

    hikari:
      connection-timeout: 30000
      maximum-pool-size: 30

  jpa:
    show-sql: true
    spring.jpa.generate-ddl: false

logging.level.root: INFO
logging.level.com.zalora: INFO
logging.level.org.infinispan.topology: INFO
logging.level.org.hibernate: INFO
logging.level.org.springframework.orm: INFO

server.port: 8080
management.security.enabled: false
endpoints.shutdown.enabled: true
