infinispan:
  cluster:
    name: Kamehameha
    statistics.enabled: true
    jgroups.config:
    network.address:

  hotrod:
    # Infinispan default is 10,000
    topologyLockTimeout: 30000 # ms
    topologyReplTimeout: 30000 # ms

  cache:
    primary:
      name: main
      mode: REPL_ASYNC
      stateTransferChunkSize: 128
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024
      numOwners: 3 # Amount of machines in the cluster storing the key

    secondary:
      name: session
      mode: REPL_SYNC
      stateTransferChunkSize: 128
      lock:
        timeout: 30 # Lock acquisition timeout in seconds
        concurrency: 1024
      numOwners: 3 # Amount of machines in the cluster storing the key

jgroups:
  aws: false
  jdbc:
    connection_url:
    connection_username: root
    connection_password:

server.port: 8080
logging.level.root: INFO
management.security.enabled: false
endpoints.shutdown.enabled: true

---
spring.profiles: jdbc

infinispan:
  cluster:
    jgroups.config: jgroups-jdbc.xml
