#!/bin/bash

if [ $AWS ]; then
    network_addr=`curl -s http://169.254.169.254/latest/meta-data/local-ipv4`;
    printf "Running on AWS: external address is %s\n" $network_addr
    NETWORK_FLAGS="-Dinfinispan.cluster.network.address=$network_addr -Djgroups.aws=$AWS"
fi

JAVA_OPTS="-server -Xms2816m -Xmx2816m -Djava.net.preferIPv4Stack=true -Djgroups.tcp.address=SITE_LOCAL $NETWORK_FLAGS"
java $JAVA_OPTS -jar /aloha-server.jar
